version: "3.3"

services:
  flask:
    build: ./flask
    container_name: flask
    ports: 
      - "8000:8000"
    network_mode: host

  nginx:
    build: ./nginx
    container_name: nginx
    environment: 
      - SERVER_NAME=https://container-service-1.29cj2i1l00s10.ap-south-1.cs.amazonlightsail.com/
    restart: always
    network_mode: host